07-14_rails_associations_practice/zoo_associations_app/config/routes.rb
Rails.application.routes.draw do
  # get 'animals/zoos'

  # get 'animals/index'

  # get 'animals/new'

  # get 'animals/show'

  # get 'animals/edit'

  # get 'zoos/index'

  # get 'zoos/new'

  # get 'zoos/show'

  # get 'zoos/edit'


    root 'zoos#index'

    resources :zoos do
        resources :animals
    end

#          Prefix   Verb   URI Pattern                              Controller#Action

#            root   GET    /                                        zoos#index

#            zoos   GET    /zoos(.:format)                          zoos#index
#                   POST   /zoos(.:format)                          zoos#create
#         new_zoo   GET    /zoos/new(.:format)                      zoos#new
#        edit_zoo   GET    /zoos/:id/edit(.:format)                 zoos#edit
#             zoo   GET    /zoos/:id(.:format)                      zoos#show
#                   PATCH  /zoos/:id(.:format)                      zoos#update
#                   PUT    /zoos/:id(.:format)                      zoos#update
#                   DELETE /zoos/:id(.:format)                      zoos#destroy

#     zoo_animals   GET    /zoos/:zoo_id/animals(.:format)          animals#index
#                   POST   /zoos/:zoo_id/animals(.:format)          animals#create
#  new_zoo_animal   GET    /zoos/:zoo_id/animals/new(.:format)      animals#new
# edit_zoo_animal   GET    /zoos/:zoo_id/animals/:id/edit(.:format) animals#edit
#      zoo_animal   GET    /zoos/:zoo_id/animals/:id(.:format)      animals#show
#                   PATCH  /zoos/:zoo_id/animals/:id(.:format)      animals#update
#                   PUT    /zoos/:zoo_id/animals/:id(.:format)      animals#update
#                   DELETE /zoos/:zoo_id/animals/:id(.:format)      animals#destroy



end

07-14_rails_associations_practice/zoo_associations_app/app/models/animal.rb
class Animal < ActiveRecord::Base
	belongs_to :zoo
end

07-14_rails_associations_practice/zoo_associations_app/app/models/zoo.rb
class Zoo < ActiveRecord::Base
	has_many :animals, dependent: :destroy
end

07-14_rails_associations_practice/zoo_associations_app/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

    def zoos
    end

    def index
        @zoo = Zoo.find(params[:zoo_id])
        # @animals = @zoo.animals
    end

    # when we save the animal, we give it the id of the zoo
    # so that animal is now associated with that zoo
    # animal form will show [@zoos, @animal] in the form_for...singular or plural
    def new
        # @zoo = Zoo.find(params[:zoo_id])
        find_zoo
        @animal = Animal.new
    end

    def create
        find_zoo
        # where @zoo is the animal we found from the url
        # pass in the @zoo so it knows which zoo to render
        @animal = @zoo.animals.new( animal_params )
        # @animal = @zoo.animals.create( animal_params )  # create will also work, but new & save is better for error handling
        if(@animal.save)
            redirect_to zoo_animals_path(@zoo)
        else
            render :new
        end
        
    end

    def show
        # find animal by its id
    end

    def edit

    end

    def update
        #@animal.update animal_params
        #if @animal.save
            # redirect_to zoo_animals_path(zoo)
        # else
            # 
        # end
    end

    def destroy
        #
    end


    private
        def find_animal
            @animal = Animal.find(params[:id])
        end

        def find_zoo
            @zoo = Zoo.find(params[:zoo_id])
            # our routes use :zoo_id, not :id, for the zoo id.
            # our routes use :id for the animal id
        end

        def animal_params
            params.require(:animal).permit(
                :name,
                :species,
                )
        end

end

07-14_rails_associations_practice/zoo_associations_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

07-14_rails_associations_practice/zoo_associations_app/app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
 
	before_action :find_zoo, only: [:show, :edit, :update, :destroy]

	def index
		@zoos = Zoo.all
	end

	def new
		@zoo = Zoo.new
	end

	def show
	end

	def edit
	end

	def create
		@zoo = Zoo.create zoo_params
		# flash message code here
		redirect_to zoos_path
	end

	def update
		# find_zoo
		@zoo.update( zoo_params )
		if(@zoo.save)
			redirect_to zoos_path
		else
			render :edit
		end
	end

	def destroy
		# find_zoo
		@zoo.destroy
		redirect_to zoos_path
	end


	private

		def find_zoo
			@zoo = Zoo.find(params[:id])
		end

		def zoo_params
			params.require(:zoo).permit(:name, :location, :year_opened)
		end

end

07-14_rails_associations_practice/zoo_associations_app/app/helpers/animals_helper.rb
module AnimalsHelper
end

07-14_rails_associations_practice/zoo_associations_app/app/helpers/application_helper.rb
module ApplicationHelper
end

07-14_rails_associations_practice/zoo_associations_app/app/helpers/zoos_helper.rb
module ZoosHelper
end

07-14_rails_associations_practice/zoo_associations_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZooAssociationsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- insert flash message controls here -->

<div id="navbar">
	<ul>
		<li style="list-style:none;"><%= link_to 'Home', zoos_path %></li>
		<li style="list-style:none;"><%= link_to 'Add a Zoo', new_zoo_path %></li>
	</ul>
</div>

<%= yield %>

</body>
</html>

07-14_rails_associations_practice/zoo_associations_app/app/views/zoos/_zooform.html.erb
<ul>
<%= form_for @zoo do |form| %>
	<li>
		<%= form.label 'Zoo name: ', autofocus: true %>
		<%= form.text_field :name %>
	</li>
	<li>
		<%= form.label 'Location of zoo: ' %>
		<%= form.text_field :location %>
	</li>
	<li>
		<%= form.label 'Year this zoo first opened: ' %>
		<%= form.text_field :year_opened %>
	</li>
	<li>
		<%= form.submit "Create Zoo" %>
	</li>

<% end %>
</ul>

07-14_rails_associations_practice/zoo_associations_app/app/views/zoos/edit.html.erb
<h1>Zoos#edit</h1>


<%= render "zooform" %>

07-14_rails_associations_practice/zoo_associations_app/app/views/zoos/index.html.erb
<h1>Zoos#index</h1>

<% @zoos.each do |zoo| %>
	<div>
		<ul>
			<li>Zoo: <%= zoo.name %></li>
			<li>Location: <%= zoo.location %></li>
			<li>Year opened: <%= zoo.year_opened %></li>
			<li><%= link_to "View all animals at this zoo", zoo_animals_path(zoo) %></li>
			<li><%= link_to "edit #{zoo.name}", edit_zoo_path(zoo) %></li>
			<li><%= link_to "destroy #{zoo.name}", zoo_path(zoo), method: :delete, data: {confirm: "Are you sure?"} %></li>
		</ul>
	</div>
<% end %>

07-14_rails_associations_practice/zoo_associations_app/app/views/zoos/new.html.erb
<h1>Zoos#new</h1>


<%= render "zooform" %>

07-14_rails_associations_practice/zoo_associations_app/app/views/zoos/show.html.erb
<h1>Zoos#show</h1>
<p>Find me in app/views/zoos/show.html.erb</p>